name: Bug report
description: Report a reproducible bug in NanoClaw
title: "[bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please provide enough detail to reproduce quickly.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
      placeholder: Clear and concise bug description
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal sequence to trigger the issue
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Node version, container runtime, and relevant config
      placeholder: macOS 15.x, Node 22.x, Apple Container/Docker, etc.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant logs (redact secrets)
      render: shell
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-checks
      options:
        - label: I searched existing issues
          required: true
        - label: I removed/redacted secrets from logs
          required: true
